libqf/plugins/plugins.pro

Because all of QML modules import this module.
So they didn't load when qmlwidgets are disabled from build.
Tested only on Windows.

Once again enable build of qmlwidgets

---

quickevent/app/plugins/qml/Receipts/src/Receipts/receiptsplugin.cpp

This fixes printing bad loss time on receipts after missing punch. (issue #54 )

Fix of bad loss times on receipts

---

libsiut/src/device/sidevicedriver.cpp
libsiut/src/device/sidevicedriver.h
quickevent/app/plugins/qml/CardReader/src/cardreaderwidget.cpp

Tak zde je ta slíbená oprava vyčítání bez zapnutého auto send. Přidal jsem tam ještě posílání ACK po úspěšném vyčtení, aby ta krabička zapípala.
Testoval jsem to pro čipy verze 5 a 6. Ještě by to radši měl někdo vyzkoušet u čipů verze 8/9 a 10/11. Podle dokumentace by to takto fungovat mělo, ale jistota je jistota.

Fix of non-autosend readout

---

quickevent/app/plugins/qml/Event/src/Event/eventplugin.cpp

Commit 78865b742dd71 broke event setup sequence which manifested itself with
following messages in application debugging output:
88<WARN>[query.cpp:30] "2 values for 1 columns Unable to execute statement"
89<WARN>[query.cpp:60] " Parameter count mismatch"
It is disturbing that this error passed unnoticed.

eventplugin: Fix SQL statement

---

libqf/libqfqmlwidgets/src/framework/mainwindow.h
libqf/libqfqmlwidgets/src/framework/partswitch.cpp
libqf/libqfqmlwidgets/src/reports/processor/reportitemimage.cpp
libsiut/src/device/sidevicedriver.cpp
quickevent/app/plugins/qml/Classes/src/editcoursecodeswidget.cpp
quickevent/app/plugins/qml/Runs/src/drawing/ganttscene.cpp
quickevent/app/plugins/qml/Runs/src/runstableitemdelegate.cpp
quickevent/app/src/main.cpp
quickshow/main.cpp
tools/qsqlmon/src/driver/qfhttpmysql/qfhttpmysql.h
tools/qsqlmon/src/sqldock.h

Coverity has identified several instances of coding errors in QuickEvent code.  The most serious were uninitialized class members.  This patch set contains both plain fixes and code cleanup.  Please review.
https://scan.coverity.com/projects/quickbox

Coverity scan fixes

---

quickevent/app/src/tablemodellogdevice.cpp

Commit 082a6a21cf4c changed the default category name.  The same name must be
known to the application log window.

Fix logging into application window (issue #233)

---

quickevent/app/plugins/qml/Receipts/src/receiptsprinter.cpp
quickevent/app/plugins/qml/Receipts/src/receiptsprinteroptions.cpp
quickevent/app/plugins/qml/Receipts/src/receiptsprinteroptions.h
quickevent/app/plugins/qml/Receipts/src/receiptsprinteroptionsdialog.cpp
quickevent/app/plugins/qml/Receipts/src/receiptsprinteroptionsdialog.ui

I've added possibility to print tickets on Epson character printers that are connected to network instead of LPT. This was pretty easy, because data format accepted by Epson printers on TCP port 9100 is the same as on LPT. 
I've also added Epson TM-U220B to the models combo box on printer options dialog and made it change the line length to 40 characters when selected.

Printing tickets on character printers connected to network.

---

libqf/libqfqmlwidgets/src/tableview.cpp

This missing condition lead to reloading invalid row, when rowExternallySaved(id, mode) is called with id which doesn't exist in the table and there is no line selected in the table.
I came to this situation when trying to register new competitor using Card reader. After reading a card Edit Competitor dialog appeared, clicking on E1 button then caused a crash.

Fixed crash on reloading invalid row in rowExternallySaved()

---

quickevent/app/plugins/qml/Event/src/eventdialogwidget.ui

Anglicke nazvy disciplin jsou prejaty z pravidel IOF, pripadne vystupu ORISu,
ktery vedle ciselneho identifikatoru discipliny vraci i cesky a anglicky nazev.
Pridan identifikator pro druzstva. Z beznych disciplin zatim zustava nepokryty NOB s id 9.

Oprava nazvu disciplin z ORISu

---

quickevent/app/plugins/Runs/qml/reports/startList_classes_nstages.qml
quickevent/app/plugins/Runs/qml/reports/startList_clubs.qml
quickevent/app/plugins/Runs/qml/reports/startList_clubs_nstages.qml
quickevent/app/plugins/Runs/src/runsplugin.cpp

Přidal jsem ještě možnost tisknout startovní čísla v reportu kluby n etap (+ popisky sloupců).
Opravena funkčnost checkboxu "Exclude DISQ" u tisku výsledků aktuální etapy + aktuální etapy pro komentátora.
Souvisí s #113 a #511

Startovní čísla u reportu kluby n etap, opraven checkbox "Exclude DISQ"

---

quickevent/app/plugins/Competitors/src/competitorwidget.cpp
quickevent/app/plugins/Competitors/src/competitorwidget.ui

Pokud se nyní změní v dialogu pro edit závodníka čip, tak se nepřenastaví u jednotlivých rozběhů, což dává smysl u víceetapových závodů, u těch samostatných však ne.
=> pokud je jen jeden "run" tedy jednoetový závod, propagovat zmenu cipu i do runs

if there is only one "run", propagate widget SI card change

---

quickevent/app/plugins/Competitors/src/competitorwidget.cpp
quickevent/app/plugins/Competitors/src/competitorwidget.h

Přepisoval jsem aby častěji fungovalo automatické vybírání kategorie. např. věk 17 se dokáže přeřadit i k H18, pokud není tak H21.. či pro veterány naopak 48 k H45.
Často (možná nikdy) však k samotnému pokusu o vybrání ani nedojde, neprojde se přes podmínku `!doc->isDirty(QStringLiteral("classId")`. Pořádně nevím, co kontroluje, ale asi nefunguje dle očekávání. Pomoc vítána.
```c++
void CompetitorWidget::onRegistrationSelected(const QVariantMap &values)
{
qfLogFuncFrame();
auto *doc = dataController()->document();
for(auto s : {"firstname", "lastname", "registration", "licence", "siid"}) {
qfDebug() << "\t" << s << "->" << values.value(s);
doc->setValue(s, values.value(s));
}
if(!doc->isDirty(QStringLiteral("classId"))) {
QString class_name_prefix = …
```

improve class suggestion

---

quickevent/app/plugins/Event/src/eventplugin.cpp

I wanted to be strict and prevent user entering the application if database is not connected. However, when a modal is opened it is not possible to exit or close the application (https://bugreports.qt.io/browse/QTBUG-29915), so it was not possible to exit the application without first connection to database/choosing the working directory. In order not to restrict the user from exiting the application I scraped the idea of prohibiting access, but at least introduced a convenient warning, that connection to database is needed and left a hint where to find this setting later.
edit: + disable menu when database is not connected

warn user that connection to database is needed when exiting connection dialog

---

quickevent/app/plugins/Event/src/eventplugin.cpp

fixed for various cases:
- given event name is in db => open straight (same as now)
- db is empty => do not display open dialog, guide user to create or open event
- db has events => show open dialog (same as now)
- open dialog canceled => current event stays opened #487
and  disable edit and export menu items when no event is currently selected

refactor event open

---

libquickevent/libquickeventgui/src/si/siidedit.cpp
libquickevent/libquickeventgui/src/si/siidedit.h

Currently, when SI card number edit box is cleared and you leave the edit box, the SI card number appears again. It is not possible to just clear the editing field unless the card number is set explicitly to 0.
this commit makes it so when SI card number is cleared, it is set to 0 instead.
code inspiration: https://codereview.qt-project.org/c/qt/qtbase/+/121767

allow clearing spinbox when editing SI card number

---

.github/workflows/c-cpp.yml

set-env command replaced by `$GITHUB_ENV`
> The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning found: https://github.com/Quick-Event/quickbox/actions/runs/291335975

Updated deprecated command in GitHub actions

---

quickevent/app/plugins/Receipts/src/receiptsplugin.cpp

Po přiřazení neznámého čipu se zapnutým autoprintem je nyní volána špatná metoda pro tisk lístečků – vytisknou se data čipu, ne mezičasy.

Oprava tisku lístečku po přiřazení - fix #331

---

datafiles.pri

V současné době se při buildu nezavolá robocopy (minimálně se nevolá u mě a ani na github actions podle logu). V instačním souboru potom nejsou qml soubory, ikony, ...

Opraven build pro windows

---

libqf/libqfcore/src/core/string.h

```
warning: implicitly-declared ‘qf::core::String& qf::core::String::operator=(const qf::core::String&)’ is deprecated [-Wdeprecated-copy]
```

fix deprecated implicit copy assignment operator

---

libqf/libqfcore/src/model/sqltablemodel.cpp
libqf/libqfcore/src/model/tablemodel.cpp

fix warnings reported in IDE
`Qt::BackgroundColorRole` and `Qt::TextColorRole` are obsolete
https://doc.qt.io/qt-5/qt.html#ItemDataRole-enum

fix obsolete Qt::ItemDataRole values

---

quickevent/app/plugins/Runs/src/eventstatisticswidget.cpp

right now solves two issues.
1) 3rd best time was incorrectly calculated even if finished runners count was less than 3 as `MAX(TOP 3)`
2) TimeToClose should now display 0 if all runners finished (even if there are less than 3), display nothing if there is no enough information to do the calculation or display calculated timeToClose down to 0.

fix TimeToClose shows zero, resolve #578

---

quickevent/app/plugins/Runs/qml/reports/startList_classes.qml
quickevent/app/plugins/Runs/qml/reports/startList_clubs.qml
quickevent/app/plugins/Runs/qml/reports/startList_clubs_nstages.qml
quickevent/app/plugins/Runs/qml/reports/startList_starters.qml

Změny:
- určitým sloupcům jsem zmenšil šířku, aby při tisku startovních listin se startovními čísly nedocházelo k nežádoucímu zalamování jmen
- pokud je číslo SI čipu 0, tak není zobrazeno ve startovní listině (týká se především vakantů)

Úprava layoutu startovních listin

---

quickevent/app/plugins/Runs/src/eventstatisticswidget.cpp

all runners finished => 0
not enough info to calculate => blank
_ > TimeToClose (can be negative)

allow negative TimeToClose, resolve #552

---

libqf/libqfqmlwidgets/src/dialogs/dialog.cpp
quickevent/app/plugins/Event/src/eventplugin.cpp

make Ok button the default in the connectToSqlServer/ConnectDbDialogWidget, so one can open the event just by pressing enter, when the application starts

set Ok button as default in connect to db dialog

---

quickevent/app/plugins/Receipts/src/receiptsplugin.cpp
quickevent/app/plugins/Receipts/src/receiptsplugin.h
quickevent/app/plugins/Receipts/src/receiptsprinter.cpp
quickevent/app/plugins/Receipts/src/receiptsprinter.h
quickevent/app/plugins/Receipts/src/receiptswidget.cpp
quickevent/app/plugins/Receipts/src/receiptswidget.h

1) change `autoprint` feature to print only the currently inserted SI Card, resolve #503 (use `print new` if you want to print all unprinted receipts so far)
2) mark receipt as *successfully printed* only if error was not encountered during the process (failed to print receipts can now be more easily printed using the `print new` button, once the issue with printer is resolved)

refactor autoprint

---

.github/workflows/c-cpp.yml

Use latest open source Qt 5.15.x version in GitHub actions. Newer Qt 5.15.x versions are avaible just for commercial licences.

Update Qt version in GitHub actions

---

quickevent/app/quickevent/plugins/Receipts/src/receiptswidget.cpp

Receipts could be loaded twice if application path and cwd directory is the same (default when run on Windows)

fix duplicate receipts loading

---

quickevent/app/quickevent/plugins/Event/src/services/emmaclient.cpp
quickevent/app/quickevent/plugins/Event/src/services/emmaclient.h
quickevent/app/quickevent/plugins/Event/src/services/emmaclientwidget.cpp
quickevent/app/quickevent/plugins/Event/src/services/emmaclientwidget.h
quickevent/app/quickevent/plugins/Event/src/services/emmaclientwidget.ui
quickevent/app/quickevent/plugins/Relays/src/addlegdialogwidget.cpp
quickevent/app/quickevent/plugins/Relays/src/addlegdialogwidget.h
quickevent/app/quickevent/plugins/Relays/src/addlegdialogwidget.ui
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

* oprava generenovani radio kodu pro txt (racom) exportu pro EmmaClient, na postgresu to padalo, opraven SQL dotaz.
* pridani oddilu do XML exportu pro EmmaClient (startovka i vysledky)
* pridani exportu XML Startovky do služby pro EmmaClient 
* uprava UI sluzby a pouziti jmena souboru z UI pro vsechny exporty
Funkcnost buildu otestovana na oblzi PBM, 24.10.2021 ( plati pro prvni 2 commity )

Oprava exportu pro EmmaClienta

---

quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp
quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.h
quickevent/app/quickevent/src/appversion.h

recently i added this line to set start times for next legs in advance
```cpp
/// set start time for next leg
setStartTimeForNextLeg(relay_id, leg, checked_card.finishTimeMs());
```
https://github.com/otahirs/quickbox/blob/dd567e5f6b358e4da30f0cffd529713d8f1c7045/quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp#L502-L503
---
so this check could be implemented
```cpp
if(is_relays) {
int run_leg = q.value("leg").toInt();
if(run_start == 0 && run_leg != 1) {
/// start time not set => this leg does not event start
qfInfo() << tr("skipping assign of SI: %1 to run_id: %2; start time not set, this leg does not event start").arg(si_id).arg(run_id);
continue;
}
}
```
https://github.com/otahirs/quickbox/blob/dd567e5f6b358e4da30f0cffd529713d8f1c7045/quickevent/app/quickevent/plug …

Fix mass start time overwrite by readout of previous leg

---

.github/workflows/c-cpp.yml

Dočasný fix - `windows-latest` se změnilo z `windows-2019` na `windows-2022` - bude potřeba důkladněji prozkoumat a zjistit příčinu problému (https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md).

Fix #758 - Fix Windows build in Github Actions

---

quickevent/app/quickevent/plugins/Event/src/services/emmaclient.cpp

Fix emma client TXT (racom) start list export
- relay cant use card start time (start need to be from previous runner)
- use relay number as id (first column)
- ignore runners in runs without class

Txt(Racom) emma service fix

---

libqf/libqfcore/src/core/logentrymap.cpp
libqf/libqfcore/src/core/logentrymap.h

/usr/include/qt/QtCore/qmetatype.h:819:9: warning: destructor called on non-final 'qf::core::LogEntryMap' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
static_cast<T*>(t)->~T();
^
/usr/include/qt/QtCore/qmetatype.h:1867:83: note: in instantiation of member function 'QtMetaTypePrivate::QMetaTypeFunctionHelper<qf::core::LogEntryMap, true>::Destruct' requested here
QtMetaTypePrivate::QMetaTypeFunctionHelper<T>::Destruct,
^
/usr/include/qt/QtCore/qmetatype.h:1896:12: note: in instantiation of function template specialization 'qRegisterNormalizedMetaType<qf::core::LogEntryMap>' requested here
return qRegisterNormalizedMetaType<T>(normalizedTypeName, dummy, defined);
^
/home/vk/git/eyas/3rdparty/quickbox/libqf/libqfcore/include/qf/core/../../../sr …

Fix clang warning

---

libsiut/src/sipunch.cpp

Nahodne jsem zjistil ze dle SPORTident Config+ je nejvyssi mozne cislo kontroly 511. Umoznuje to zapsat do kontroly, nasledne do cipu. Zvladne to i vycist.
QE zatim zvladne kod pouze do cisla 255.
Co jsem zkousel jiny vycitaci SW (si_read) tak ten to spravne nacte uz v buildu z roku 2016.
Takze to vypada ze uz se toto dlouho nezmenilo.
Zkusil jsem udelat upravu ve funkci  SIPunch::SIPunch(const QByteArray &card_data, int ix);
Zkusebni vycteni fungovalo. Zkouseno na cipu v10 a SIAC.

Extend SI punch decode - control code can be up to 511

---

CMakeLists.txt
libqf/libqfcore/CMakeLists.txt
libqf/libqfcore/src/core/collator.cpp
libqf/libqfcore/src/core/collator.h
libqf/libqfcore/src/core/utils.cpp
libqf/libqfcore/src/model/sqltablemodel.cpp
libqf/libqfcore/src/utils/table.cpp
libqf/libqfqmlwidgets/src/dialogs/previewdialog.cpp
libqf/libqfqmlwidgets/src/exporttableviewwidget.cpp
libqf/libqfqmlwidgets/src/reports/processor/reportitem_html.cpp
libqf/libqfqmlwidgets/src/reports/processor/reportitempara.cpp
libqf/libqfqmlwidgets/src/reports/processor/reportpainter.cpp
libqf/libqfqmlwidgets/src/reports/processor/reportpainter.h
libqf/libqfqmlwidgets/src/tableview.cpp
libqf/libqfqmlwidgets/src/tableviewproxymodel.cpp
libqf/libqfqmlwidgets/src/texteditwidget.cpp
tools/qsqlmon/src/dlgeditconnection.cpp

I'm not sure if I did the regexes wrong. It seems that "anchoredPattern"
is correct, because the regex was allways used with "exactMatch". I'm
not sure however about "match" and "globalMatch". In findCaptions it was
obvious (I think), but the other usages I'm not sure.

qt6: Get rid of Core5Compat

---

libqf/libqfqmlwidgets/src/framework/ipersistentsettings.cpp
libqf/libqfqmlwidgets/src/framework/ipersistentsettings.h

It's needed by classes that inherit from IPersistentSettings.

Add missing virtual dtor

---

quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.cpp
quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.h
quickevent/app/quickevent/plugins/Event/src/services/oresultsclientwidget.ui
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.h

push competitor data (including result status  - `OK, MissPunch,...`) to OResults.eu service immediately after  
readout (`DBEVENT_CARD_PROCESSED_AND_ASSIGNED`) and after competitor is saved (`DBEVENT_COMPETITOR_EDITED`) 
as most of the time sensitive data is handled by this feature, the default export interval is prolonged to 1min

feat(OResults): send runner data after readout or edit

---

quickevent/app/quickevent/plugins/Relays/src/relaysplugin.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

close #837 
1. add `Id` for `Class` to all iof xml exports
```xml
<Class>
<Id>1234</Id>
<Name>...</Name>
</Class>
```
2. unify team and organization name in iof xml export for relays. now both startlist and results follow this format
```xml
<TeamResult>
<Name>TBM 19</Name>
<Organisation>
<Name>KOS TJ Tesla Brno</Name>
<ShortName>TBM</ShortName>
</Organisation>
<BibNumber>19</BibNumber>
...
```
3. unify `director` -> `Director` and `mainReferee` -> `MainReferee` in all exports
4. add missing `type="CZE"` in individual startlist export
5. unify `StartTime`, `Director` and `mainReferee` xml nodes creation

fix: iof xml export tweaks

---

.github/workflows/c-cpp.yml
quickevent/quickevent.iss

https://github.com/Quick-Event/quickbox/blob/321f99c92e5da547aa1cd3e84513df3bb02526bc/.github/workflows/c-cpp.yml#L94
-> `mingw-w64-x86_64-openssl` package now ships updated version of SSL .dll libraries    
merge this once the pipeline cache is deleted and windows build starts to fail :)

fix: windows build ssl version

---

quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.cpp
quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.h
quickevent/app/quickevent/plugins/Event/src/services/oresultsclientwidget.cpp

1. save API key persistently in DB (`config` table). 
API key was saved in settings, which were not event specific and results could be uploaded by mistake to wrong event due to presence of API key from other previously opened event. now it is saved in DB, independently for each event.
2. compress XML payload with zlib to save bandwidth

OResults improvements

---

libqf/libqfqmlwidgets/src/dialogs/messagebox.cpp
quickevent/app/quickevent/plugins/Event/src/eventplugin.cpp

When finding out why the dialog "Open imported event" is not working properly - the event would not open after clicking the `Yes` button - I discovered a bug in the [libqf/libqfqmlwidgets/src/dialogs/messagebox.cpp](https://github.com/Quick-Event/quickbox/compare/master...otahirs:fixYesNoDialog?expand=1#diff-f68f08752bf51888d6da1c34dabd375bd40a7cfc92504ad38b0a63f9b796e436)
In addition I have set the default option for `Open imported event` as `Yes`

fix: askYesNo dialog

---

quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.cpp
quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.h
quickevent/app/quickevent/plugins/Event/src/services/oresultsclientwidget.cpp

1. make sure results and startlist does not upload to the server in the same timeframe. ~~not the best kind of serialization, but the delay should be enough.~~
2. support multi-stage events
~~2. save the `stage_id` when service was started. so change of stage does not affect the periodic exports~~

fix(OResults): serialize xml uploads, suport for multistage events

---

.github/workflows/c-cpp.yml
quickevent/quickevent.iss

budle correct version of SSL libraries for windows build.  
tested on W10 (Version 10.0.19045 Build 19045)

fix: include correct version of ssl libs for windows build

---

libqf/libqfcore/libqfcore-uk_UA.ts
libquickevent/libquickeventcore/libquickeventcore-uk_UA.ts
libquickevent/libquickeventgui/libquickeventgui-uk_UA.ts
libsiut/libsiut-uk_UA.ts
quickevent/app/quickevent/quickevent-uk_UA.ts
quickshow/quickshow-uk_UA.ts
tools/qsqlmon/qsqlmon-uk_UA.ts

Hello, I've updated the Ukrainian translation manually. Is this reasonable as I see the translations are usually updated with some weblate?
It's worth noting that QuickEvent is fine-tuned for Latin-based scripts, and hardly usable with Cyrillic-based languages unless I patch up the string collation routine: https://github.com/Quick-Event/quickbox/commit/6177c5e4f8bb3f1cfd6c94cff36fdab78c70979d . Could a more generic collation be implemented as an optional feature?

Update the Ukrainian translation manually

---

quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.cpp
quickevent/app/quickevent/plugins/Relays/src/relaysplugin.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp
quickevent/app/quickevent/src/appversion.h

unify runner id exports to OResults across start-list/results upload and `onCompetitorChanged`  
currently in start-list/results uploads, runners can be exported with ORIS temporary entry number  
but in `onCompetitorChanged` these are not considered valid and card_num is used instead
this creates problems as runners with ORIS temporary entry number are not exported under one unique Id  
to solve this, `onCompetitorChanged`  has been changed to allow for ORIS temporary entry number

fix(OResults): unify runner_id

---

libquickevent/libquickeventcore/src/runstatus.cpp
quickevent/app/quickevent/src/appversion.h

fix toString methods producing "???" as a result status. Why would we use `???` instead of a default value anyway?  
there is an unsolved question how the runners got `isDisqualified` flag, without any other more concrete flag set in #917

fix: ??? in RunStatus

---

quickevent/app/quickevent/src/appversion.h
quickevent/make-dist.sh

temporal fix until Qt6 build gets stable
include libcrypto and libssl (v1.1) from ubuntu 20.04 in the release appimage to support new linux distros that do come only with uncompatible openssl 3.0
close #925 
tested on ubuntu 22.04

fix: include libssl in appimage

---

libquickevent/libquickeventcore/src/codedef.cpp
libquickevent/libquickeventcore/src/codedef.h
libquickevent/libquickeventgui/src/reportoptionsdialog.cpp
libquickevent/libquickeventgui/src/reportoptionsdialog.h
libquickevent/libquickeventgui/src/reportoptionsdialog.ui
quickevent/app/quickevent/plugins/Relays/qml/reports/results.qml
quickevent/app/quickevent/plugins/Relays/qml/reports/results_condensed.qml
quickevent/app/quickevent/plugins/Relays/qml/reports/startList_classes.qml
quickevent/app/quickevent/plugins/Relays/qml/reports/startList_clubs.qml
quickevent/app/quickevent/plugins/Runs/qml/reports/competitorsWithCardRent.qml
quickevent/app/quickevent/plugins/Runs/qml/reports/results_nstages.qml
quickevent/app/quickevent/plugins/Runs/qml/reports/results_nstagesSpeaker.qml
quickevent/app/quickevent/plugins/Runs/qml/reports/startList_starters.qml
quickevent/app/quickevent/plugins/Runs/src/eventstatisticswidget.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

- Fix page layouts for use with receipt printer
- ReportOptionsDialog  
- add Reset button
- add select start number for print startlist by classes and for starters
Affects #805, #253, #213, #373

Fix page layouts & some ReportOptionsDialog improvements

---

libqf/libqfcore/CMakeLists.txt
libqf/libqfcore/src/core/core.pri
libqf/libqfcore/src/core/log.cpp
libqf/libqfcore/src/core/log.h

Having these defined in the header and somewhere else NOT in the header (libshv) causes linking issues in Windows.

qfcore: logging: Define functions in a cpp file

---

.github/workflows/installer.yml
quickevent/app/quickevent/plugins/Event/src/services/emmaclient.cpp
quickevent/app/quickevent/plugins/Runs/src/runswidget.cpp

Fix issue #953, better computation of start time for Emma Client (racom type). Fix when runs.startTimeMs is null.
Fix issue #954, add missing ReportOptionsDialog PageLayout call
And try to fix windows installer action (Qt 6.6.3)

Fix issues 953 & 954 for QE3

---

.github/actions/appimage/action.yml
.github/actions/cmake/action.yml
.github/actions/run-linter/action.yml
.github/workflows/appimage.yml
.github/workflows/installer.yml
.github/workflows/lint.yml

Updated build to actions v4.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Fixed builds :
- AppImage
- Installer
- Lint

QE3 - Update build - replaced deprecated Node.js version.

---

.github/workflows/c-cpp.yml
quickevent/make-dist.sh

In action there was 3 warnings :
* build_linux
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/upload-artifact@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
* build_linux
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, actions/upload-artifact@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
* Deprecation notice: v1, v2, and v3 of the artifact actions
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: …

Update build - replaced deprecated Node.js version

---

libquickevent/libquickeventcore/src/runstatus.h
quickevent/app/quickevent/plugins/Relays/src/relaysplugin.cpp
quickevent/app/quickevent/src/appversion.h

Fix for incomplete relays.
TeamMemberResult - One element per relay leg must be included, even if the team has not assigned any team member to the leg.
[IOF XML datastandard v3 - Ln2580](https://github.com/international-orienteering-federation/datastandard-v3/blob/24eb108e4c6b5e2904e5f8f0e49142e45e2c5230/IOF.xsd#L2580)

Fix XML export for relays.

---

libqf/libqfcore/CMakeLists.txt

.qm files for libqfcore are now generated on build.

Add missing qm translation files generation for libqfcore

---

libqf/libqfcore/src/core/utils.cpp
libqf/libqfcore/src/core/utils.h
quickevent/app/quickevent/plugins/Classes/src/drawing/ganttitem.cpp
quickevent/app/quickevent/plugins/Event/src/eventplugin.cpp
quickevent/app/quickevent/plugins/Event/src/stage.h
quickevent/app/quickevent/src/application.cpp
quickevent/app/quickevent/src/application.h
quickevent/app/quickevent/src/appversion.h

Don't know when this stopped to work

Fix class layout load
