quickevent/app/plugins/qml/CardReader/src/cardreaderwidget.cpp

Changes default value of SI contol port to empty. Than by default it uses first found port.

Changes default value of si control port.

---

libsiut/src/device/commport.cpp
quickevent/app/plugins/qml/CardReader/src/cardreaderwidget.cpp

I've fixed setting comm port parity and loading of comm port settings.

Small fixes of card reader

---

quickevent/app/plugins/qml/Competitors/qml/reports/competitorsStatistics.qml
quickevent/app/plugins/qml/Runs/qml/StartLists.qml
quickevent/app/plugins/qml/Runs/src/eventstatisticswidget.cpp

Fixed prints.
Some UI mods for better reading.

Some improvements & fixes

---

libqf/libqfcore/libqfcore.cs_CZ.ts
libqf/libqfqmlwidgets/libqfqmlwidgets.cs_CZ.ts
quickevent/app/plugins/qml/CardReader/CardReader.cs_CZ.ts
quickevent/app/plugins/qml/Classes/Classes.cs_CZ.ts
quickevent/app/plugins/qml/Competitors/Competitors.cs_CZ.ts
quickevent/app/plugins/qml/Event/Event.cs_CZ.ts
quickevent/app/plugins/qml/Receipts/Receipts.cs_CZ.ts
quickevent/app/plugins/qml/Runs/Runs.cs_CZ.ts
quickevent/app/plugins/qml/attic/Logging/Logging.cs_CZ.ts
tools/qsqlmon/qsqlmon.cs_CZ.ts

**Poznámky k překladu:**
**1)** Našel jsem 2x soubor Oris.cs_CZ.ts ?
● první umístění: quickbox\quickevent\app\plugins\qml\attic\Oris
● druhé: quickbox\quickevent\app\plugins\qml\Oris
**2)** V souboru Competitors.cs_CZ.ts jsou přepisy a nejdou opravit
● konktrétně v RegistrationsWidget:
- Filter --> Flitr --> Filtr
- Registration --> Regisrační číslo --> Registrační číslo
**3)** V Luži jsme se bavili, že "Not competing" (NC) znamená mimo soutěž a "Off race in this stage", že neběží tuto etapu, takže to jsem taky upravil

Další úprava (aktualizace) překladů

---

quickevent/app/plugins/qml/Runs/qml/Results.qml

Oprava formatu IOF XML Result - jenom pridano NotCompeting

IOF XML Result update - added NotCompeting

---

quickevent/app/plugins/qml/Runs/qml/reports/results_stage_awards.qml

As a result award printing was broken.
122<INFO>[qmllogsingleton.cpp:31] "runs printCurrentStageAwards triggered"
123<INFO>[catalog.cpp:108] loading field info for table: "clubs"
124<INFO>[reportprocessor.cpp:367] Adding ReportProcessor QML engine import path: "/data/src/build-quickbox-Qt_5_5_1_System-Debug/bin/../lib/qml"
125<INFO>[reportprocessor.cpp:367] Adding ReportProcessor QML engine import path: "/data/src/build-quickbox-Qt_5_5_1_System-Debug/bin/../lib/qml/quickevent"
126<ERR>[reportprocessor.cpp:65] Erorr loading report component: "file:///data/src/build-quickbox-Qt_5_5_1_System-Debug/lib/qml/quickevent/Runs/reports/results_stage_awards.qml:-1 File not found\n"
127<WARN>(default) QQmlComponent: Component is not ready
128<ERR>[reportprocessor.cpp:114] Error creating root object …

QE: Fix absolute symlink

---

quickevent/app/plugins/qml/CardReader/CardReader.cs_CZ.ts
quickevent/app/plugins/qml/Competitors/Competitors.cs_CZ.ts
quickevent/app/plugins/qml/Event/Event.cs_CZ.ts
quickevent/app/plugins/qml/ExampleCppQml/ExampleCppQml.cs_CZ.ts
quickevent/app/plugins/qml/ExamplePureQml/ExamplePureQml.cs_CZ.ts
quickevent/app/plugins/qml/Oris/Oris.cs_CZ.ts
quickevent/app/plugins/qml/Receipts/Receipts.cs_CZ.ts
quickevent/app/plugins/qml/Runs/Runs.cs_CZ.ts
quickevent/app/plugins/qml/Speaker/Speaker.cs_CZ.ts

Revert "Edited translations"

---

libqf/libqfcore/src/utils/clioptions.cpp
libqf/libqfqmlwidgets/src/frame.cpp
libqf/libqfqmlwidgets/src/framework/partswitch.cpp
libqf/libqfqmlwidgets/src/reports/processor/reportitemdetail.cpp
libqf/libqfqmlwidgets/src/reports/processor/reportpainter.cpp
libqf/libqfqmlwidgets/src/reports/processor/style/pen.cpp
libqf/libqfqmlwidgets/src/tableview.cpp
quickevent/app/plugins/qml/Classes/src/editcoursecodeswidget.cpp
quickevent/app/plugins/qml/Receipts/src/receiptsprinter.cpp
quickevent/app/plugins/qml/Runs/src/Runs/runsplugin.cpp
tools/qfsqldbfs/src/dbfsfuseops.cpp

Next round of fixes based on Coverity Scan results.  Please review.

Coverity scan fixes

---

quickevent/app/plugins/qml/Runs/src/runstablemodel.cpp
quickevent/app/plugins/qml/Runs/src/runstablemodel.h
quickevent/app/plugins/qml/Runs/src/runstablewidget.cpp
quickevent/app/plugins/qml/Runs/src/runswidget.cpp
quickevent/app/plugins/qml/Runs/src/runswidget.h

Regional championship rules impose certain principles on start list draw. http://psob.dig.cz/dokumenty/sr2013.pdf
Supersedes pull request #116.

Prague Region Competition Rules - new start list draw modes

---

quickevent/app/plugins/qml/Runs/src/runswidget.cpp

Program losuje do startovky i lidi off-race fixed

---

devutils/lctools/lctool.sh
quickevent/app/plugins/qml/CardReader/src/cardreaderwidget.cpp
quickevent/app/plugins/qml/Classes/src/classeswidget.cpp
quickevent/app/plugins/qml/Runs/qml/main.qml
quickevent/app/plugins/qml/Runs/src/runswidget.cpp

Hope that everywhere could be tr() function invoked.

All menu items are translatable

---

quickevent/app/plugins/qml/Classes/src/classdefwidget.ui
quickevent/app/plugins/qml/Relays/src/Relays/relaysplugin.cpp
quickevent/app/plugins/qml/Relays/src/relayswidget.cpp
quickevent/app/plugins/qml/Relays/src/relaywidget.ui
quickevent/app/plugins/qml/Runs/qml/Results.qml
quickevent/app/plugins/qml/Runs/qml/StartLists.qml
quickevent/app/plugins/qml/Runs/src/runswidget.cpp
quickevent/app/plugins/qml/Runs/src/runswidget.ui

if possible, update TS files in order to finish czech localization, thanks

Some strings are no longer translatable + typos

---

quickevent/app/plugins/qml/Runs/Runs.cs_CZ.ts
quickevent/app/plugins/qml/Runs/Runs.nb_NO.ts
quickevent/app/plugins/qml/Runs/Runs.nl_BE.ts
quickevent/app/plugins/qml/Runs/Runs.pl_PL.ts
quickevent/app/plugins/qml/Runs/Runs.ru_RU.ts
quickevent/app/plugins/qml/Runs/src/eventstatisticswidget.cpp

improved event stats labels for Time 1, Time 3

---

quickevent/app/plugins/qml/Runs/Runs.cs_CZ.ts
quickevent/app/plugins/qml/Runs/Runs.nb_NO.ts
quickevent/app/plugins/qml/Runs/Runs.nl_BE.ts
quickevent/app/plugins/qml/Runs/Runs.pl_PL.ts
quickevent/app/plugins/qml/Runs/Runs.ru_RU.ts
quickevent/app/plugins/qml/Runs/src/eventstatisticswidget.cpp
quickevent/app/plugins/qml/Runs/src/runswidget.cpp

je pro fungovování `edit on punch` být potřeba v `Entries` módu?

"show off" onhover text changed fvacek/quickbox#457

---

quickevent/make-dist.sh

Upravil jsem script pro sestavení AppImage, tak aby se dal používat tebou jako dřív (zůstaly defaultní cesty), ale přidal jsem argumenty a nápovědu, aby šel jednodušeji použít i ostatními.

appImage build script improvement

---

quickevent/make-dist.sh

omylem jsem jiným  merge requestem přepsal původní změny
uprava scriptu na dytvoření AppImage

close #493

---

quickevent/app/plugins/Relays/Relays.pro

Make it buildable under Windows

Added missing dependency (Windows)

---

quickevent/app/plugins/Event/src/eventplugin.cpp

návrh na přidání timeoutu pro připojení k databázi na 30s, uprav dle libosti

add timeout for database connection #501

---

quickevent/app/plugins/Competitors/src/competitorswidget.cpp
quickevent/app/plugins/Relays/src/relayswidget.cpp
quickevent/app/plugins/Runs/src/runswidget.cpp

při startu aplikace zobrazit defaultně všechny závodníky místo první kategorie

select  --- all --- classes on startup

---

quickevent/app/plugins/CardReader/src/cardcheckerfreeordercpp.cpp
quickevent/app/plugins/CardReader/src/cardcheckerfreeordercpp.h
quickevent/app/plugins/CardReader/src/cardreaderplugin.cpp
quickevent/app/plugins/CardReader/src/src.pri

https://github.com/fvacek/quickbox/issues/508
TODO: add possibility to use alt control code

Added Free order card checker

---

quickevent/app/plugins/Runs/src/runsplugin.cpp

include NumberOfControls in startlist IOF v3 XML export #308

---

quickevent/app/plugins/Receipts/src/receiptswidget.cpp

error info as default #331

---

quickevent/app/plugins/Competitors/src/competitorwidget.cpp

https://github.com/Quick-Event/quickbox/pull/539#discussion_r397485368

improve chance to match gender in class suggestion

---

quickevent/app/plugins/Classes/src/editcourseswidget.cpp

fix cotrol count and code display in Classes -> Edit -> Courses

---

quickevent/app/plugins/CardReader/src/cardreaderwidget.cpp
quickevent/app/plugins/Receipts/src/receiptsplugin.cpp
quickevent/app/plugins/Receipts/src/receiptsplugin.h
quickevent/app/plugins/Receipts/src/receiptswidget.cpp
quickevent/app/plugins/Receipts/src/receiptswidget.h

print sicard when assigning runner if autoprint is enabled #331

---

quickevent/app/plugins/Event/src/connectdbdialogwidget.ui

edited event id label
added padding
edited placeholders

beautify database connection dialog

---

quickevent/app/plugins/CardReader/src/cardreaderwidget.cpp
quickevent/app/plugins/Runs/src/findrunnerwidget.ui

1. 
missing space in `
"UPDATE runs SET siId=" QF_IARG(si_id) " WHERE competitorId=" QF_IARG(competitor_id) "AND stageId>=" QF_IARG(stage_id);
`
=> 
`[exception.cpp:44]|W|  UPDATE runs SET siId=416029 WHERE competitorId=129AND stageId>=1
unrecognized token: "129AND" Unable to execute statement `
2.
update si in runs table for current stage when SI card is assigned, close #424

fix exception due to typo in SQL string and resolve #424

---

libqf/libqfqmlwidgets/src/spinbox.cpp
libqf/libqfqmlwidgets/src/spinbox.h

need testing on windows @xkenia 
#66

make spinbox number input independant of keyboard locale #66

---

.github/workflows/c-cpp.yml

https://github.com/Quick-Event/quickbox/issues/564#issuecomment-693526488

github actions | build for linux and windows

---

quickevent/app/plugins/CardReader/src/cardreaderwidget.cpp

It might be a good idea to print the receipt after the name is actually updated in the database :sweat_smile:

fix assigncard autoprint receipt

---

datafiles.pri

Reverts Quick-Event/quickbox#569

Revert "Update datafiles.pri"

---

quickevent/app/plugins/Classes/src/classeswidget.cpp
quickevent/app/plugins/Receipts/src/receiptswidget.ui

Added Q_OBJECT macro to make `tr` function work, improved english localization (mentioned in #331).

Add Q_OBJECT macro

---

quickevent/quickevent.iss

Added necrolog to installer.

---

quickevent/app/plugins/Runs/src/eventstatisticswidget.cpp

fix invalid equality operator

---

libqf/libqfcore/src/utils/table.cpp
libqf/libqfqmlwidgets/src/reports/widgets/reportviewwidget.cpp
libqf/libqfqmlwidgets/src/tableview.cpp
quickevent/app/plugins/Runs/src/runsplugin.cpp
tools/qsqlmon/src/mainwindow.cpp

needed by Qt 5.12.11 on Windows

include QTextStream

---

quickhttpd/src/appclioptions.cpp
quickhttpd/src/appclioptions.h
quickhttpd/src/main.cpp
quickshow/src/appclioptions.cpp
quickshow/src/appclioptions.h
quickshow/src/main.cpp

Add locale param to quickhttpd and quickshow

---

quickevent/app/quickevent/quickevent-cs_CZ.ts
quickevent/app/quickevent/quickevent-fr_FR.ts
quickevent/app/quickevent/quickevent-nb_NO.ts
quickevent/app/quickevent/quickevent-nl_BE.ts
quickevent/app/quickevent/quickevent-pl_PL.ts
quickevent/app/quickevent/quickevent-ru_RU.ts
quickevent/app/quickevent/quickevent-uk_UA.ts
quickevent/app/quickevent/quickevent.pro
quickevent/app/quickevent/src/main.cpp

Reworked #635 - translations are embedded into the application.

Add qtbase translations v2

---

quickevent/app/quickevent/plugins/Receipts/src/receiptswidget.cpp

fix: remove double equality operator from SQL expresion

---

quickevent/app/quickevent/plugins/Runs/qml/results_stage.qml
quickevent/app/quickevent/plugins/Runs/qml/results_stageSpeaker.qml
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

Add number of finished runners to stage results

---

quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

Add BibNumber to IOF XML 3.0 startlist export

---

quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp

this change disallows automatic readout if the readout finish time from SI card is different from previous readouts, error is thrown with prompt for manual assign
ps: when two runners run with the same SI card, the second one will be always prompted for manual assign
ps2: if two runners have the same SI card and finnishTime1 < startTime2, no action is required

disallow automatic results overwrite, fix #636

---

quickevent/app/quickevent/plugins/CardReader/src/cardreaderwidget.cpp
quickevent/app/quickevent/plugins/CardReader/src/cardreaderwidget.ui
quickevent/app/quickevent/plugins/Classes/src/classeswidget.ui
quickevent/app/quickevent/plugins/Competitors/src/competitorswidget.ui
quickevent/app/quickevent/plugins/Event/src/eventplugin.cpp
quickevent/app/quickevent/plugins/Receipts/src/receiptswidget.cpp
quickevent/app/quickevent/plugins/Receipts/src/receiptswidget.ui
quickevent/app/quickevent/plugins/Relays/src/relayswidget.ui
quickevent/app/quickevent/plugins/Runs/src/eventstatisticswidget.ui
quickevent/app/quickevent/plugins/Runs/src/runstablewidget.ui
quickevent/app/quickevent/plugins/Runs/src/runswidget.ui
quickevent/app/quickevent/plugins/Speaker/src/speakerwidget.ui

1. unified margins on tables, so they do not jump around that much when switching modules
2. removed few frame borders, that are not needed (Classes and Speaker table)
3. set min width to service dock, so it opens in usable state
https://user-images.githubusercontent.com/24588500/144764455-e2f2abdf-f5a7-43df-9bdf-bd41a5f4d0b9.mp4
https://user-images.githubusercontent.com/24588500/144764461-af906a7a-7ea4-4fc0-b46f-512d29044b46.mp4

small cosmetic changes

---

libquickevent/libquickeventgui/src/si/siidedit.cpp
libquickevent/libquickeventgui/src/si/siidedit.h
quickevent/app/quickevent/plugins/Relays/src/addlegdialogwidget.ui

transform SiCard value from 0 to Empty in edit competitor widget

---

quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp
quickevent/app/quickevent/src/appversion.h

Modified XML export -added more information in XML3.0 export (Organisation\Name, Result\TimeBehind, Result\ControlCard)

Issue #724 - added more information in XML3.0

---

libqf/libqfcore/src/utils/htmlutils.cpp

Add call toHtmlEscaped for item value and attributes value to fix XML export.

Fix issue #751 - XML export use escaping

---

quickevent/app/quickevent/plugins/CardReader/src/cardreaderwidget.cpp

Fix #752 - fix SQL update statement for PostgreSQL

---

quickevent/app/quickevent/plugins/Classes/src/classesplugin.cpp
quickevent/app/quickevent/plugins/Classes/src/classesplugin.h
quickevent/app/quickevent/plugins/Classes/src/classeswidget.cpp

Upravuje chovani pri importu trati, nyni se krome plneho nahrazeni trati da i importem pridat dalsi trate.
Doted import vzdy smazal starsi trate.

Courses import update - new cources can replace old cources or be append

---

quickevent/app/quickevent/plugins/Event/src/eventdialogwidget.cpp
quickevent/app/quickevent/plugins/Event/src/eventplugin.cpp

Fix #737 - Allow only small letters in PostgreSQL schema name

---

quickevent/app/quickevent/plugins/Classes/src/drawing/ganttitem.cpp
quickevent/app/quickevent/src/appversion.h

Fix #766 - fix SQL query for class items in drawing tool

---

libquickevent/libquickeventcore/include/quickevent/core/exporters/stageresultscsvexporter.h
libquickevent/libquickeventcore/src/exporters/exporters.pri
libquickevent/libquickeventcore/src/exporters/fileexporter.cpp
libquickevent/libquickeventcore/src/exporters/fileexporter.h
libquickevent/libquickeventcore/src/exporters/htmlfileexporter.cpp
libquickevent/libquickeventcore/src/exporters/htmlfileexporter.h
libquickevent/libquickeventcore/src/exporters/stageresultscsvexporter.cpp
libquickevent/libquickeventcore/src/exporters/stageresultscsvexporter.h
quickevent/app/quickevent/plugins/Runs/src/services/resultsexporter.cpp
quickevent/app/quickevent/plugins/Runs/src/services/resultsexporter.h
quickevent/app/quickevent/plugins/Runs/src/services/resultsexporterwidget.cpp
quickevent/app/quickevent/plugins/Runs/src/services/resultsexporterwidget.ui

Added CSV result export in result service - single file CSV or one file per class

Result service - csv export of results

---

.github/workflows/c-cpp.yml

Na základě diskuze z https://github.com/Quick-Event/quickbox/pull/778

Fix Windows CI build

---

quickevent/app/quickevent/plugins/Relays/src/relaysplugin.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

Remove Time element from IOF XML 3.0 export if SplitTime is missing

---

quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

Fix issue #738 - hide start number column in html startlist when no start number in class / club

Fix issue #738 - hide start number column in html startlist

---

quickevent/app/quickevent/plugins/Event/src/eventplugin.cpp
quickevent/app/quickevent/plugins/Event/src/services/emmaclient.cpp
quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.cpp
quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.h
quickevent/app/quickevent/plugins/Event/src/services/oresultsclientwidget.cpp
quickevent/app/quickevent/plugins/Event/src/services/oresultsclientwidget.h
quickevent/app/quickevent/plugins/Event/src/services/oresultsclientwidget.ui
quickevent/app/quickevent/plugins/Event/src/services/services.pri
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.h

Together with @Jurda5, we are developing a new live results service similar to liveresultat.orientering.se, but hopefully more friendly for both users and organizers, also including tight integration with the Bluebox radio controls.  
That being said, we need a new service in QuickEvent for uploading the finish times and result status for runners, this MR should cover that.

feat: OResults service

---

quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.cpp

fix: OResults error message

---

quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

fix: unify time export format

---

quickevent/app/quickevent/plugins/Runs/src/runflagsdialog.cpp
quickevent/app/quickevent/plugins/Runs/src/runflagsdialog.h
quickevent/app/quickevent/plugins/Runs/src/runflagsdialog.ui
quickevent/app/quickevent/plugins/Runs/src/runstablemodel.cpp

resolve  #796, close #714
status is displayed as one of `OK`, `Disqualified`, `Not competing`

refactor: improve run flags dialog

---

quickevent/app/quickevent/plugins/Runs/src/cardflagsdialog.cpp
quickevent/app/quickevent/plugins/Runs/src/cardflagsdialog.h
quickevent/app/quickevent/plugins/Runs/src/cardflagsdialog.ui

refactor: improve card flags 

---

quickevent/app/quickevent/plugins/CardReader/src/cardchecker.cpp
quickevent/app/quickevent/plugins/CardReader/src/cardreaderwidget.cpp
quickevent/app/quickevent/plugins/CardReader/src/cardreaderwidget.h
quickevent/app/quickevent/plugins/Classes/src/classestableview.cpp
quickevent/app/quickevent/plugins/Competitors/src/competitorwidget.cpp
quickevent/app/quickevent/plugins/Event/src/services/oresultsclientwidget.cpp
quickevent/app/quickevent/plugins/Receipts/src/receiptswidget.cpp
quickevent/app/quickevent/plugins/Relays/src/relaywidget.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp
quickevent/app/quickevent/plugins/Runs/src/runstableitemdelegate.cpp
quickevent/app/quickevent/plugins/Runs/src/runswidget.cpp

Remove some unused includes
Fix debug Test button in CardReaderWidget

Include cleanup & debug button fix

---

libqf/libqfcore/src/utils/treeitembase.h
libqf/libqfqmlwidgets/src/internal/dlgtableviewcopyspecial.h
libqf/libqfqmlwidgets/src/internal/tableviewcopytodialogwidget.h
libqf/libqfqmlwidgets/src/reports/widgets/itemvalueeditorwidget.h
libqf/plugins/core/src/model/sqldatadocument.cpp
qsicli/src/dlgsettings.h
quickevent/app/quickevent/plugins/CardReader/src/cardreadersettingspage.h
quickevent/app/quickevent/plugins/Receipts/src/receiptssettingspage.h
tools/qsqlmon/src/columnselectorwidget.h
tools/qsqlmon/src/dlgindexdef.h

Oops. The file is not built with CMake, so I didn't rename the call.
Also remove some unneeded semicolons.

Fix more warnings

---

libqf/libqfcore/src/core/stacktrace.cpp

Remove unused variable

---

quickevent/app/quickevent/plugins/Relays/src/relaysplugin.cpp

do not include `!isRunning` competitors in position calculation  
hide empty legs from xml export  
hide competitors that did not finished (OK status && no finish time) from xml export
resolve #853, resolve #854

fix: relay xml results export

---

quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp

Set start time for next leg on readout

---

quickevent/app/quickevent/plugins/Core/src/coreplugin.cpp

#862 need more info about SSL library.

More info about SSL in About Dlg

---

quickevent/app/quickevent/plugins/Competitors/src/competitorswidget.cpp
quickevent/app/quickevent/plugins/Event/qml/DbSchema.qml
quickevent/app/quickevent/plugins/Oris/src/orisimporter.cpp
quickevent/app/quickevent/plugins/Relays/src/relaysplugin.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp
quickevent/app/quickevent/src/application.cpp

Add :
- IOF ID column to DB
- import IOF ID from ORIS by JSON
- export IOF ID in Startlist and results

Add IOF ID into QE - for WRE events

---

quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp

fix: startlist dlg for classes & clubs, close #879

---

quickevent/app/quickevent/plugins/Event/src/services/oresultsclient.cpp

fix incorrectly set context object and `multi_part` memory leak

fix: context, multipart leak

---

libquickevent/libquickeventgui/src/reportoptionsdialog.cpp
libquickevent/libquickeventgui/src/reportoptionsdialog.h
libquickevent/libquickeventgui/src/reportoptionsdialog.ui
quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp
quickevent/app/quickevent/plugins/Runs/src/runsplugin.h

Feature request from #739
Now are possible 3 basic types : by Class Names, by Start times, by Runner names

Improved club start list sorting, close #739

---

quickevent/app/quickevent/plugins/Classes/src/drawing/classitem.cpp
quickevent/app/quickevent/plugins/Event/src/eventplugin.cpp
quickevent/app/quickevent/quickevent-cs_CZ.ts
quickevent/app/quickevent/quickevent-fr_FR.ts
quickevent/app/quickevent/quickevent-nb_NO.ts
quickevent/app/quickevent/quickevent-nl_BE.ts
quickevent/app/quickevent/quickevent-pl_PL.ts
quickevent/app/quickevent/quickevent-ru_RU.ts
quickevent/app/quickevent/quickevent-uk_UA.ts

- small UI improvement (see screenshot below)
- add possibility to translate 2 window titles
- update ts files

Small UI improvement, localization

---

libquickevent/libquickeventgui/src/reportoptionsdialog.ui

Improved club start list sorting (fix), close #739

---

libquickevent/libquickeventcore/js/ogtime.js
quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp

- Fixed the cause of problems reported in the issue described in #917
- Fixed ogtime.js functions as suggested in #917 to match behavior with the edit in PR #919

Additional code modifications related to RunStatus fixes, close #917

---

quickshow/src/application.cpp
quickshow/src/cellrenderer.cpp
quickshow/src/model.cpp

Added relays results into Quickshow

Added relays into Quickshow

---

quickshow/src/application.cpp
quickshow/src/cellrenderer.cpp
quickshow/src/model.cpp

Added relays into QE3 QuickShow

Add relays into QE3 quickshow

---

quickevent/app/quickevent/plugins/Event/src/services/emmaclient.cpp
quickevent/app/quickevent/src/appversion.h

Fix when runs.startTimeMs is null

Fix issue #953, better computation of start time for Emma Client (racom type)

---

quickevent/app/quickevent/plugins/Event/src/eventdialogwidget.ui
quickevent/app/quickevent/plugins/Oris/src/txtimporter.cpp
quickevent/app/quickevent/plugins/Oris/src/xmlimporter.cpp
quickevent/app/quickevent/plugins/Relays/src/relayswidget.cpp
quickevent/app/quickevent/plugins/Relays/src/relayswidget.h
quickevent/app/quickevent/quickevent-cs_CZ.ts
quickevent/app/quickevent/quickevent-fr_FR.ts
quickevent/app/quickevent/quickevent-nb_NO.ts
quickevent/app/quickevent/quickevent-nl_BE.ts
quickevent/app/quickevent/quickevent-pl_PL.ts
quickevent/app/quickevent/quickevent-ru_RU.ts
quickevent/app/quickevent/quickevent-uk_UA.ts
quickevent/app/quickevent/src/appversion.h

Add Import of start numbers (bibs) from CSV for relays.

Relay import start numbers

---

CMakeLists.txt
quickevent/app/quickevent/CMakeLists.txt
quickevent/app/quickevent/plugins/Event/src/eventdialogwidget.ui
quickevent/app/quickevent/plugins/Oris/src/txtimporter.cpp
quickevent/app/quickevent/plugins/Oris/src/xmlimporter.cpp
quickevent/app/quickevent/plugins/Relays/src/relayswidget.cpp
quickevent/app/quickevent/plugins/Relays/src/relayswidget.h
quickevent/app/quickevent/quickevent-cs_CZ.ts
quickevent/app/quickevent/quickevent-fr_FR.ts
quickevent/app/quickevent/quickevent-nb_NO.ts
quickevent/app/quickevent/quickevent-nl_BE.ts
quickevent/app/quickevent/quickevent-pl_PL.ts
quickevent/app/quickevent/quickevent-ru_RU.ts
quickevent/app/quickevent/quickevent-uk_UA.ts

Add Import of start numbers (bibs) from CSV for relays.
QE3 branch

Relay import start numbers qe3

---

quickevent/app/quickevent/CMakeLists.txt

(otherwise compilation fails in linking phase)

Add missing sources (xmlimporter, qropunch) to quickevent/CMakeLists.txt

---

.github/workflows/installer.yml

Windows 2022 -> 2025
PSQL 14 -> 17
QT 6.8.2 -> 6.8.3
OpenSSL 1.1.1 -> 3.1.4

Update Windows action build settings.

---

quickevent/app/quickevent/plugins/Receipts/src/receiptsplugin.cpp

Try to fix issue #1023 - Špatné aktuální pořadí na lístečcích při stejném pořadí

Fix issues 1023 for branch QE3

---

quickevent/app/quickevent/plugins/Classes/src/classeswidget.cpp
quickevent/app/quickevent/plugins/Classes/src/editcourseswidget.cpp
quickevent/app/quickevent/plugins/Classes/src/editcourseswidget.h
quickevent/app/quickevent/src/appversion.h

Some courses invisible in course edit form
